-- FloppyUI Profiles
-- Stores the ElvUI profile data that the installer applies.
--
-- These are NOT encoded import strings -- they are plain Lua tables, taken
-- from ElvUI's "Lua Table" export. The installer (ElvUI.lua) writes them
-- directly into ElvUI's database, which avoids ElvUI's own import popups.
--
-- Each ElvUI export contains only the values that DIFFER from ElvUI's
-- defaults, so the installer must MERGE these tables over the defaults
-- rather than replacing entire tables.
--
-- HOW TO UPDATE A TABLE:
--   1. In-game: /ec  ->  Profiles  ->  Export
--   2. Export Type: "Lua Table"
--   3. Copy everything between the outer { } (without the trailing
--      "::profile::Name" marker) and replace the matching table below.
--   4. Save the file and reload (/floppy reload).
--
-- NOTE: Healing is intentionally left empty for now and will be added later.

local _, FloppyPrivate = ...

FloppyPrivate.Profiles = {}

----------------------------------------------------------------------
-- ElvUI layout profiles
----------------------------------------------------------------------
-- DpsTank bundles the three layout-related exports:
--   profile = E.db      (unitframes, actionbars, nameplates, layout, ...)
--   private = E.private (skins, module toggles, theme, ...)
--   global  = E.global  (account-wide shared data, datatext panels, ...)

FloppyPrivate.Profiles.ElvUI = {

	DpsTank = {

		-- profile :: written into the named profile "FloppyUI-DpsTank"
		profile = {
			["WT"] = {
				["announcement"] = {
					["keystone"] = { ["enable"] = false },
					["utility"]  = { ["enable"] = false },
				},
				["combat"] = {
					["combatAlert"] = {
						["animation"] = false,
						["animationSize"] = 0.2,
						["font"] = { ["style"] = "SHADOWOUTLINE" },
					},
					["damageMeterLayout"] = {
						["animation"] = { ["enable"] = false },
						["autoSwitch"] = {
							["rules"] = { ["delve"] = 1, ["outOfCombat"] = 1 },
						},
						["enable"] = true,
						["height"] = 450,
						["layouts"] = {
							[1] = {
								["innerPadding"] = 0,
								["meters"] = { [1] = { ["weight"] = 5 } },
							},
						},
						["shadow"] = false,
						["width"] = 450,
					},
					["raidMarkers"] = {
						["backdrop"] = false,
						["backdropSpacing"] = 1,
						["buttonAnimation"] = false,
						["countDownTime"] = 10,
						["enable"] = false,
						["spacing"] = 1,
						["visibility"] = "INPARTY",
					},
				},
				["item"] = {
					["contacts"]      = { ["enable"] = false },
					["extraItemsBar"] = { ["enable"] = false },
					["inspect"]       = { ["enable"] = false },
					["itemLevel"]     = { ["enable"] = false },
					["trade"]         = { ["enable"] = false },
				},
				["maps"] = {
					["eventTracker"] = {
						["stormarionAssault"] = { ["alert"] = false },
					},
				},
				["misc"] = {
					["gameBar"] = { ["enable"] = false },
				},
				["quest"] = {
					["achievementTracker"] = { ["show"] = false },
					["autoCollapse"] = {
						["dungeon"]  = "collapse",
						["raid"]     = "collapse",
						["scenario"] = "collapse",
					},
					["switchButtons"] = {
						["announcement"] = false,
						["font"] = { ["style"] = "SHADOWOUTLINE" },
					},
					["turnIn"] = { ["enable"] = false },
				},
				["social"] = {
					["chatBar"]  = { ["enable"] = false },
					["chatLink"] = { ["enable"] = false },
					["chatText"] = {
						["bnetFriendOnline"] = false,
						["classIcon"] = false,
						["factionIcon"] = false,
						["guildMemberStatus"] = false,
					},
					["emote"]      = { ["enable"] = false },
					["friendList"] = { ["enable"] = false },
					["smartTab"]   = { ["enable"] = false },
				},
				["tooltips"] = {
					["elvUITweaks"] = {
						["betterMythicPlusInfo"] = { ["enable"] = false },
						["raceIcon"] = { ["enable"] = false },
						["specIcon"] = { ["enable"] = false },
					},
					["groupInfo"] = { ["enable"] = false },
					["keystone"]  = { ["enable"] = false },
				},
			},
			["actionbar"] = {
				["bar1"] = { ["buttonSize"] = 38, ["buttonSpacing"] = 0 },
				["bar2"] = {
					["buttonSize"] = 38,
					["buttonSpacing"] = 0,
					["enabled"] = true,
					["visibility"] = "[petbattle] hide; show",
				},
				["bar3"] = {
					["buttonSize"] = 36,
					["buttonSpacing"] = 0,
					["buttons"] = 12,
					["buttonsPerRow"] = 12,
					["visibility"] = "[petbattle] hide; show",
				},
				["bar4"] = {
					["backdrop"] = false,
					["buttonSize"] = 36,
					["buttonSpacing"] = 0,
					["buttonsPerRow"] = 12,
					["visibility"] = "[petbattle] hide; show",
				},
				["bar5"] = {
					["buttonSpacing"] = 0,
					["buttons"] = 12,
					["buttonsPerRow"] = 3,
					["mouseover"] = true,
					["visibility"] = "[petbattle] hide; show",
				},
				["bar6"] = {
					["buttonSize"] = 30,
					["buttonSpacing"] = 0,
					["buttons"] = 4,
					["enabled"] = true,
					["showGrid"] = false,
					["visibility"] = "[petbattle] hide; show",
				},
				["barPet"] = {
					["backdrop"] = false,
					["buttonSize"] = 28,
					["buttonSpacing"] = 0,
					["buttonsPerRow"] = 10,
				},
				["font"] = "Expressway",
				["stanceBar"] = {
					["buttonSize"] = 28,
					["buttonSpacing"] = 0,
					["buttons"] = 5,
				},
			},
			["auras"] = {
				["buffs"] = {
					["countFont"] = "Expressway",
					["countFontSize"] = 14,
					["size"] = 40,
				},
				["debuffs"] = {
					["countFont"] = "Expressway",
					["countFontSize"] = 14,
					["size"] = 40,
				},
			},
			["bags"] = {
				["bagSize"] = 42,
				["bagWidth"] = 474,
				["bankSize"] = 42,
				["bankWidth"] = 474,
				["countFont"] = "Expressway",
				["countFontSize"] = 14,
				["itemLevelCustomColorEnable"] = true,
				["itemLevelFont"] = "Expressway",
				["itemLevelFontSize"] = 14,
				["scrapIcon"] = true,
				["split"] = {
					["bag1"] = true,
					["bag2"] = true,
					["bag3"] = true,
					["bag4"] = true,
					["bagSpacing"] = 7,
					["player"] = true,
				},
				["vendorGrays"] = { ["enable"] = true },
			},
			["chat"] = {
				["copyChatLines"] = true,
				["emotionIcons"] = false,
				["font"] = "Expressway",
				["fontOutline"] = "SHADOWOUTLINE",
				["fontSize"] = 14,
				["keywords"] = "",
				["maxLines"] = 500,
				["panelBackdrop"] = "LEFT",
				["panelHeight"] = 235,
				["panelWidth"] = 520,
				["tabFont"] = "Expressway",
				["tabFontOutline"] = "OUTLINE",
				["tabSelectorColor"] = { ["b"] = 0.99, ["g"] = 0.99, ["r"] = 0.99 },
				["timeStampFormat"] = "%H:%M:%S ",
				["timeStampLocalTime"] = true,
			},
			["convertPages"] = true,
			["databars"] = {
				["azerite"] = { ["enable"] = false },
				["experience"] = {
					["height"] = 25,
					["showBubbles"] = true,
					["textFormat"] = "CURREM",
					["width"] = 1200,
				},
				["honor"] = { ["enable"] = false },
				["threat"] = {
					["enable"] = false,
					["height"] = 24,
					["width"] = 472,
				},
			},
			["datatexts"] = {
				["font"] = "Expressway",
				["fontOutline"] = "SHADOWOUTLINE",
				["fontSize"] = 14,
				["panels"] = {
					["LeftChatDataPanel"] = { [3] = "LDB_BugSack" },
					["MinimapPanel"] = { [1] = "Time", [2] = "System" },
					["RightChatDataPanel"] = { ["enable"] = false },
					["TopLeft"] = {
						[1] = "LDB_QueueRoleAutoAccept",
						[2] = "LDB_KeystoneLoot",
						[3] = "LDB_Leatrix_Plus",
						[4] = "LDB_WeeklyKnowledge",
						[5] = "LDB_Nys_ToDoList",
						[6] = "LDB_AlterEgo",
						["battleground"] = false,
						["enable"] = true,
					},
				},
			},
			["general"] = {
				["addonCompartment"] = { ["hide"] = true },
				["afk"] = false,
				["autoRepair"] = "GUILD",
				["bonusObjectivePosition"] = "AUTO",
				["bottomPanel"] = false,
				["font"] = "Expressway",
				["fontSize"] = 14,
				["fontStyle"] = "SHADOWOUTLINE",
				["fonts"] = {
					["objective"] = {
						["enable"] = true,
						["outline"] = "SHADOWOUTLINE",
						["size"] = 20,
					},
					["questtext"] = {
						["enable"] = true,
						["outline"] = "OUTLINE",
					},
					["questtitle"] = {
						["enable"] = true,
						["size"] = 20,
					},
				},
				["guildBank"] = {
					["countFont"] = "Expressway",
					["countFontOutline"] = "SHADOWOUTLINE",
					["countFontSize"] = 12,
					["itemLevelFont"] = "Expressway",
					["itemLevelFontOutline"] = "SHADOWOUTLINE",
					["itemLevelFontSize"] = 12,
				},
				["itemLevel"] = {
					["itemLevelFont"] = "Expressway",
					["itemLevelFontOutline"] = "SHADOWOUTLINE",
					["itemLevelFontSize"] = 14,
					["showOnItem"] = true,
					["totalLevelFont"] = "Expressway",
					["totalLevelFontOutline"] = "SHADOWOUTLINE",
				},
				["loginmessage"] = false,
				["minimap"] = {
					["icons"] = {
						["crafting"]   = { ["xOffset"] = -3, ["yOffset"] = 0 },
						["difficulty"] = { ["xOffset"] = 3,  ["yOffset"] = 0 },
						["mail"] = {
							["scale"] = 1.2,
							["xOffset"] = -3,
							["yOffset"] = 0,
						},
						["tracking"] = {
							["position"] = "BOTTOMRIGHT",
							["scale"] = 1.5,
							["xOffset"] = -3,
						},
					},
					["locationFontOutline"] = "SHADOWOUTLINE",
					["locationFontSize"] = 20,
					["resetZoom"] = { ["enable"] = true, ["time"] = 15 },
					["scale"] = 1.1,
					["size"] = 220,
				},
				["objectiveFrameHeight"] = 400,
				["privateAuras"] = {
					["enable"] = false,
					["icon"] = { ["size"] = 42 },
				},
				["resurrectSound"] = true,
				["tagUpdateRate"] = 0.5,
				["talkingHeadFrameScale"] = 1,
				["totems"] = {
					["growthDirection"] = "HORIZONTAL",
					["size"] = 50,
					["spacing"] = 8,
				},
				["valuecolor"] = { ["b"] = 0.99, ["g"] = 0.99, ["r"] = 0.99 },
			},
			["movers"] = {
				["AddonCompartmentMover"] = "RIGHT,ElvUI_MinimapHolder,RIGHT,-5,10",
				["AlertFrameMover"] = "TOP,ElvUIParent,TOP,0,-250",
				["AltPowerBarMover"] = "TOP,ElvUIParent,TOP,0,-41",
				["ArenaHeaderMover"] = "TOPRIGHT,UIParent,TOPRIGHT,-320,-280",
				["AzeriteBarMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-3,-246",
				["BNETMover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,0,260",
				["BelowMinimapContainerMover"] = "TOPRIGHT,UIParent,TOPRIGHT,-4,-280",
				["BossBannerMover"] = "TOP,ElvUIParent,TOP,0,-126",
				["BossButton"] = "BOTTOM,ElvUIParent,BOTTOM,0,180",
				["BossHeaderMover"] = "TOPRIGHT,UIParent,TOPRIGHT,-320,-280",
				["BuffsMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-250,0",
				["DTPanelTopLeftMover"] = "TOPLEFT,ElvUIParent,TOPLEFT,0,0",
				["DebuffsMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-250,-168",
				["DurabilityFrameMover"] = "TOPLEFT,ElvUIParent,TOPLEFT,141,-4",
				["ElvAB_1"] = "BOTTOM,ElvUIParent,BOTTOM,-230,0",
				["ElvAB_2"] = "BOTTOM,ElvUIParent,BOTTOM,230,0",
				["ElvAB_3"] = "BOTTOM,ElvUIParent,BOTTOM,218,38",
				["ElvAB_4"] = "BOTTOM,ElvUIParent,BOTTOM,-218,38",
				["ElvAB_5"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,520,0",
				["ElvAB_6"] = "BOTTOM,ElvUIParent,BOTTOM,-300,418",
				["ElvUF_AssistMover"] = "TOPLEFT,ElvUIParent,TOPLEFT,4,-249",
				["ElvUF_FocusCastbarMover"] = "TOPLEFT,ElvUF_Focus,BOTTOMLEFT,0,-1",
				["ElvUF_FocusMover"] = "BOTTOM,ElvUIParent,BOTTOM,-322,380",
				["ElvUF_PartyMover"] = "BOTTOM,UIParent,BOTTOM,0,240",
				["ElvUF_PetCastbarMover"] = "TOPLEFT,ElvUF_Pet,BOTTOMLEFT,0,-1",
				["ElvUF_PetMover"] = "BOTTOM,UIParent,BOTTOM,0,123",
				["ElvUF_PlayerCastbarMover"] = "BOTTOM,ElvUIParent,BOTTOM,0,395",
				["ElvUF_PlayerMover"] = "BOTTOM,ElvUIParent,BOTTOM,-375,447",
				["ElvUF_Raid1Mover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,0,430",
				["ElvUF_Raid2Mover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,0,430",
				["ElvUF_Raid3Mover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,0,430",
				["ElvUF_TankMover"] = "TOPLEFT,ElvUIParent,TOPLEFT,4,-187",
				["ElvUF_TargetCastbarMover"] = "BOTTOM,ElvUIParent,BOTTOM,375,426",
				["ElvUF_TargetMover"] = "BOTTOM,ElvUIParent,BOTTOM,375,447",
				["ElvUF_TargetTargetMover"] = "BOTTOM,ElvUIParent,BOTTOM,322,380",
				["ElvUIBagMover"] = "BOTTOMRIGHT,RightChatPanel,BOTTOMRIGHT,0,26",
				["ElvUIBankMover"] = "BOTTOMLEFT,LeftChatPanel,BOTTOMLEFT,0,26",
				["EventToastMover"] = "TOP,ElvUIParent,TOP,0,-150",
				["ExperienceBarMover"] = "TOP,ElvUIParent,TOP,0,0",
				["GMMover"] = "TOPLEFT,ElvUIParent,TOPLEFT,251,-5",
				["HonorBarMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-2,-251",
				["LeftChatMover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,0,0",
				["LootFrameMover"] = "TOPRIGHT,UIParent,TOPRIGHT,-320,-280",
				["LossControlMover"] = "BOTTOM,ElvUIParent,BOTTOM,0,550",
				["MinimapMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,0,0",
				["MirrorTimer1Mover"] = "TOP,ElvUIParent,TOP,-1,-96",
				["ObjectiveFrameMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-163,-325",
				["PetAB"] = "BOTTOM,ElvUIParent,BOTTOM,0,75",
				["PowerBarContainerMover"] = "TOP,ElvUIParent,TOP,0,-75",
				["PrivateAurasMover"] = "TOP,UIParent,TOP,0,-704",
				["PrivateRaidWarningMover"] = "TOP,RaidBossEmoteFrame,TOP,0,0",
				["QueueStatusMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-215,-210",
				["ReputationBarMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-2,-243",
				["RightChatMover"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-4,4",
				["ShiftAB"] = "BOTTOM,ElvUIParent,BOTTOM,-364,74",
				["SocialMenuMover"] = "TOPLEFT,ElvUIParent,TOPLEFT,4,-187",
				["ThreatBarMover"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-4,4",
				["TooltipMover"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-450,0",
				["TopCenterContainerMover"] = "TOP,ElvUIParent,TOP,0,-30",
				["TotemTrackerMover"] = "BOTTOMLEFT,UIParent,BOTTOMLEFT,640,120",
				["VOICECHAT"] = "TOPLEFT,ElvUIParent,TOPLEFT,369,-210",
				["VehicleLeaveButton"] = "BOTTOM,ElvUIParent,BOTTOM,418,75",
				["VehicleSeatMover"] = "TOPLEFT,ElvUIParent,TOPLEFT,4,-4",
				["WTCombatAlertFrameMover"] = "TOP,UIParent,TOP,0,-615",
				["WTDamageMeterLayoutMover"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,0,0",
				["WTMinimapButtonBarAnchor"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,0,-265",
				["WTRaidMarkersBarAnchor"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,0,250",
				["WTSwitchButtonBarMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-22,-308",
				["ZoneAbility"] = "BOTTOM,ElvUIParent,BOTTOM,150,301",
			},
			["nameplates"] = {
				["colors"] = {
					["castNoInterruptColor"] = { ["a"] = 1 },
					["selection"] = {
						[0] = { ["b"] = 0.25, ["g"] = 0.25, ["r"] = 0.78 },
						[2] = { ["b"] = 0.36, ["g"] = 0.76, ["r"] = 0.85 },
						[3] = { ["b"] = 0.3,  ["g"] = 0.67, ["r"] = 0.29 },
					},
					["threat"] = {
						["badColor"]        = { ["b"] = 0.25, ["g"] = 0.25, ["r"] = 0.78 },
						["goodColor"]       = { ["b"] = 0.3,  ["g"] = 0.67, ["r"] = 0.29 },
						["goodTransition"]  = { ["b"] = 0.36, ["g"] = 0.76, ["r"] = 0.85 },
					},
				},
				["font"] = "Expressway",
				["units"] = {
					["ENEMY_NPC"] = {
						["health"] = { ["text"] = { ["format"] = "" } },
					},
					["ENEMY_PLAYER"] = {
						["health"] = { ["text"] = { ["format"] = "" } },
						["portrait"] = {
							["classicon"] = false,
							["enable"] = true,
							["position"] = "LEFT",
							["xOffset"] = 0,
							["yOffset"] = 0,
						},
					},
				},
			},
			["tooltip"] = {
				["alwaysShowRealm"] = true,
				["fadeOut"] = false,
				["font"] = "Expressway",
				["headerFont"] = "Expressway",
				["headerFontSize"] = 14,
				["healthBar"] = {
					["font"] = "Expressway",
					["statusPosition"] = "DISABLED",
				},
				["itemCount"] = { ["bank"] = true, ["stack"] = true },
				["mythicDataEnable"] = false,
				["showMount"] = false,
				["smallTextFontSize"] = 14,
				["targetInfo"] = false,
				["textFontSize"] = 14,
				["yOffset"] = 0,
			},
			["unitframe"] = {
				["colors"] = {
					["auraBarBuff"] = {
						["b"] = 0.22745099663734,
						["g"] = 0.11764706671238,
						["r"] = 0.76862752437592,
					},
					["castClassColor"] = true,
					["castColor"] = {
						["a"] = 1, ["b"] = 0.31, ["g"] = 0.31, ["r"] = 0.31,
					},
					["debuffHighlight"] = {
						["Bleed"]   = { ["a"] = 1, ["b"] = 0.60000002384186, ["g"] = 0.20000001788139 },
						["Curse"]   = { ["a"] = 1, ["r"] = 0.60000002384186 },
						["Disease"] = { ["a"] = 1, ["g"] = 0.40000003576279, ["r"] = 0.60000002384186 },
						["Magic"]   = { ["a"] = 1, ["g"] = 0.60000002384186, ["r"] = 0.20000001788139 },
						["Poison"]  = { ["a"] = 1, ["g"] = 0.60000002384186 },
					},
					["healPrediction"] = {
						["absorbs"] = { ["a"] = 1 },
						["maxOverflow"] = 1,
					},
					["healthclass"] = true,
				},
				["font"] = "Expressway",
				["units"] = {
					["assist"] = { ["enable"] = false },
					["boss"] = {
						["buffs"] = {
							["enable"] = false,
							["maxDuration"] = 300,
							["sizeOverride"] = 27,
							["yOffset"] = 16,
						},
						["castbar"] = {
							["customTextFont"] = {
								["enable"] = true,
								["font"] = "Expressway",
								["fontSize"] = 16,
							},
							["customTimeFont"] = {
								["enable"] = true,
								["font"] = "Expressway",
								["fontSize"] = 16,
							},
							["format"] = "CURRENTMAX",
							["height"] = 20,
							["icon"] = false,
							["width"] = 246,
							["xOffsetText"] = 0,
							["xOffsetTime"] = 0,
						},
						["customTexts"] = {
							["BossHealth"] = {
								["attachTextTo"] = "Frame",
								["enable"] = true,
								["font"] = "Expressway",
								["fontOutline"] = "SHADOWOUTLINE",
								["justifyH"] = "CENTER",
								["size"] = 24,
								["text_format"] = "||cFF29CC00[health:current:shortvalue] - [perhp<%]||r",
								["xOffset"] = 0,
								["yOffset"] = 0,
							},
							["BossName"] = {
								["attachTextTo"] = "Health",
								["enable"] = true,
								["font"] = "Expressway",
								["fontOutline"] = "SHADOWOUTLINE",
								["justifyH"] = "LEFT",
								["size"] = 22,
								["text_format"] = "[classcolor][name]",
								["xOffset"] = 2,
								["yOffset"] = 30,
							},
							["BossPower"] = {
								["attachTextTo"] = "Frame",
								["enable"] = true,
								["font"] = "Expressway",
								["fontOutline"] = "SHADOWOUTLINE",
								["justifyH"] = "CENTER",
								["size"] = 18,
								["text_format"] = "[power:current:shortvalue] / [power:max:shortvalue]",
								["xOffset"] = 0,
								["yOffset"] = -24,
							},
						},
						["debuffs"] = {
							["enable"] = false,
							["maxDuration"] = 300,
							["sizeOverride"] = 27,
							["yOffset"] = -16,
						},
						["health"] = { ["text_format"] = "", ["xOffset"] = 0 },
						["height"] = 65,
						["infoPanel"] = { ["height"] = 17 },
						["name"] = { ["text_format"] = "" },
						["power"] = { ["height"] = 18, ["text_format"] = "" },
						["spacing"] = 35,
						["width"] = 246,
					},
					["focus"] = {
						["CombatIcon"] = { ["enable"] = false },
						["castbar"] = { ["enable"] = false, ["width"] = 165 },
						["customTexts"] = {
							["FocusName"] = {
								["attachTextTo"] = "Health",
								["enable"] = true,
								["font"] = "Expressway",
								["fontOutline"] = "SHADOWOUTLINE",
								["justifyH"] = "CENTER",
								["size"] = 20,
								["text_format"] = "[name]",
								["xOffset"] = 0,
								["yOffset"] = 0,
							},
						},
						["debuffs"] = { ["enable"] = false },
						["healPrediction"] = { ["enable"] = false },
						["name"] = { ["text_format"] = "" },
						["power"] = { ["enable"] = false },
						["width"] = 165,
					},
					["party"] = {
						["CombatIcon"] = { ["enable"] = true },
						["buffIndicator"] = { ["enable"] = false },
						["customTexts"] = {
							["PartyHealth"] = {
								["attachTextTo"] = "Health",
								["enable"] = false,
								["font"] = "Expressway",
								["fontOutline"] = "MONOCHROMEOUTLINE",
								["justifyH"] = "CENTER",
								["size"] = 10,
								["text_format"] = "",
								["xOffset"] = 0,
								["yOffset"] = 0,
							},
							["PartyName"] = {
								["attachTextTo"] = "Frame",
								["enable"] = true,
								["font"] = "Expressway",
								["fontOutline"] = "SHADOWOUTLINE",
								["justifyH"] = "CENTER",
								["size"] = 20,
								["text_format"] = "[name:abbrev:medium]",
								["xOffset"] = 0,
								["yOffset"] = 38,
							},
							["PartyPower"] = {
								["attachTextTo"] = "Power",
								["enable"] = true,
								["font"] = "Expressway",
								["fontOutline"] = "SHADOWOUTLINE",
								["justifyH"] = "LEFT",
								["size"] = 20,
								["text_format"] = "[perpp<%]",
								["xOffset"] = 2,
								["yOffset"] = 5,
							},
						},
						["debuffs"] = {
							["anchorPoint"] = "BOTTOMLEFT",
							["countFont"] = "Expressway",
							["countFontOutline"] = "SHADOWOUTLINE",
							["countFontSize"] = 14,
							["countYOffset"] = 0,
							["growthY"] = "DOWN",
							["perrow"] = 6,
							["sizeOverride"] = 30,
							["yOffset"] = -2,
						},
						["groupBy"] = "ROLE",
						["growthDirection"] = "RIGHT_UP",
						["health"] = { ["text_format"] = "" },
						["height"] = 75,
						["horizontalSpacing"] = 5,
						["name"] = { ["text_format"] = "" },
						["power"] = { ["height"] = 15, ["text_format"] = "" },
						["privateAuras"] = { ["enable"] = false },
						["rdebuffs"] = { ["font"] = "Expressway" },
						["roleIcon"] = {
							["position"] = "TOPLEFT",
							["size"] = 20,
							["xOffset"] = 1,
							["yOffset"] = -1,
						},
						["startFromCenter"] = true,
						["width"] = 200,
					},
					["pet"] = {
						["castbar"] = { ["enable"] = false, ["iconSize"] = 32 },
						["disableTargetGlow"] = false,
						["healPrediction"] = { ["enable"] = false },
						["infoPanel"] = { ["height"] = 14 },
						["power"] = { ["enable"] = false },
						["width"] = 270,
					},
					["player"] = {
						["CombatIcon"] = {
							["anchorPoint"] = "TOPRIGHT",
							["size"] = 40,
						},
						["RestIcon"] = {
							["size"] = 24,
							["texture"] = "Resting0",
							["xOffset"] = 0,
							["yOffset"] = 0,
						},
						["aurabar"] = { ["enable"] = false },
						["buffs"] = { ["attachTo"] = "FRAME" },
						["castbar"] = {
							["customTextFont"] = {
								["enable"] = true,
								["font"] = "Expressway",
								["fontSize"] = 20,
								["fontStyle"] = "SHADOWTHICKOUTLINE",
							},
							["customTimeFont"] = {
								["enable"] = true,
								["font"] = "Expressway",
								["fontSize"] = 20,
								["fontStyle"] = "SHADOWTHICKOUTLINE",
							},
							["height"] = 25,
							["icon"] = false,
							["insideInfoPanel"] = false,
							["width"] = 400,
							["yOffsetText"] = -1,
							["yOffsetTime"] = -1,
						},
						["classbar"] = { ["enable"] = false, ["height"] = 14 },
						["customTexts"] = {
							["PlayerAbsorb"] = {
								["attachTextTo"] = "Health",
								["enable"] = true,
								["font"] = "Expressway",
								["fontOutline"] = "SHADOWOUTLINE",
								["justifyH"] = "RIGHT",
								["size"] = 20,
								["text_format"] = "[absorbs:shortvalue]",
								["xOffset"] = 0,
								["yOffset"] = -20,
							},
							["PlayerHealth"] = {
								["attachTextTo"] = "Health",
								["enable"] = true,
								["font"] = "Expressway",
								["fontOutline"] = "SHADOWOUTLINE",
								["justifyH"] = "LEFT",
								["size"] = 24,
								["text_format"] = "||cFF29CC00[health:current:shortvalue] - [perhp<%]||r",
								["xOffset"] = 0,
								["yOffset"] = 0,
							},
							["PlayerName"] = {
								["attachTextTo"] = "Health",
								["enable"] = false,
								["font"] = "Expressway",
								["fontOutline"] = "MONOCHROMEOUTLINE",
								["justifyH"] = "CENTER",
								["size"] = 10,
								["text_format"] = "",
								["xOffset"] = 0,
								["yOffset"] = 0,
							},
							["PlayerPower"] = {
								["attachTextTo"] = "Health",
								["enable"] = false,
								["font"] = "Expressway",
								["fontOutline"] = "MONOCHROMEOUTLINE",
								["justifyH"] = "CENTER",
								["size"] = 10,
								["text_format"] = "",
								["xOffset"] = 0,
								["yOffset"] = 0,
							},
						},
						["debuffs"] = {
							["anchorPoint"] = "TOPRIGHT",
							["countFont"] = "Expressway",
							["countFontOutline"] = "SHADOWOUTLINE",
							["countFontSize"] = 16,
							["countYOffset"] = 0,
							["growthX"] = "LEFT",
							["yOffset"] = 35,
						},
						["disableMouseoverGlow"] = true,
						["healPrediction"] = {
							["absorbStyle"] = "REVERSED",
							["height"] = 20,
						},
						["health"] = {
							["attachTextTo"] = "InfoPanel",
							["text_format"] = "",
						},
						["height"] = 65,
						["power"] = {
							["attachTextTo"] = "InfoPanel",
							["enable"] = false,
							["height"] = 22,
						},
						["raidRoleIcons"] = { ["scale"] = 1.2 },
						["strataAndLevel"] = {
							["frameLevel"] = 2,
							["frameStrata"] = "MEDIUM",
						},
					},
					["raid1"] = {
						["customName"] = "Mythic",
						["customTexts"] = {
							["Raid1Health"] = {
								["attachTextTo"] = "Health",
								["enable"] = true,
								["font"] = "Expressway",
								["fontOutline"] = "SHADOWOUTLINE",
								["justifyH"] = "CENTER",
								["size"] = 18,
								["text_format"] = "||cFF29CC00[perhp<%]||r",
								["xOffset"] = 0,
								["yOffset"] = 0,
							},
							["Raid1Name"] = {
								["attachTextTo"] = "Frame",
								["enable"] = true,
								["font"] = "Expressway",
								["fontOutline"] = "SHADOWOUTLINE",
								["justifyH"] = "CENTER",
								["size"] = 20,
								["text_format"] = "[classcolor][name:medium:translit]",
								["xOffset"] = 0,
								["yOffset"] = 32,
							},
							["Raid1Status"] = {
								["attachTextTo"] = "Health",
								["enable"] = true,
								["font"] = "Expressway",
								["fontOutline"] = "SHADOWOUTLINE",
								["justifyH"] = "CENTER",
								["size"] = 14,
								["text_format"] = "[status]",
								["xOffset"] = 0,
								["yOffset"] = -22,
							},
						},
						["groupBy"] = "ROLE",
						["health"] = { ["text_format"] = "" },
						["height"] = 65,
						["name"] = {
							["attachTextTo"] = "InfoPanel",
							["position"] = "BOTTOMLEFT",
							["text_format"] = "",
							["xOffset"] = 2,
						},
						["numGroups"] = 4,
						["power"] = { ["height"] = 10, ["onlyHealer"] = true },
						["pvpclassificationindicator"] = { ["enable"] = false },
						["rdebuffs"] = {
							["font"] = "Expressway",
							["size"] = 30,
							["xOffset"] = 30,
							["yOffset"] = 25,
						},
						["resurrectIcon"] = { ["attachTo"] = "BOTTOMRIGHT" },
						["roleIcon"] = {
							["attachTo"] = "InfoPanel",
							["position"] = "TOPRIGHT",
							["size"] = 16,
							["yOffset"] = -1,
						},
						["verticalSpacing"] = 10,
						["width"] = 110,
					},
					["raid2"] = {
						["customTexts"] = {
							["Raid2Health"] = {
								["attachTextTo"] = "Health",
								["enable"] = true,
								["font"] = "Expressway",
								["fontOutline"] = "SHADOWOUTLINE",
								["justifyH"] = "CENTER",
								["size"] = 18,
								["text_format"] = "||cFF29CC00[perhp<%]||r",
								["xOffset"] = 0,
								["yOffset"] = 0,
							},
							["Raid2Name"] = {
								["attachTextTo"] = "Health",
								["enable"] = true,
								["font"] = "Expressway",
								["fontOutline"] = "SHADOWOUTLINE",
								["justifyH"] = "CENTER",
								["size"] = 20,
								["text_format"] = "[classcolor][name:medium:translit]",
								["xOffset"] = 0,
								["yOffset"] = 25,
							},
							["Raid2Status"] = {
								["attachTextTo"] = "Health",
								["enable"] = true,
								["font"] = "Expressway",
								["fontOutline"] = "SHADOWOUTLINE",
								["justifyH"] = "CENTER",
								["size"] = 14,
								["text_format"] = "[status]",
								["xOffset"] = 0,
								["yOffset"] = -18,
							},
						},
						["groupBy"] = "ROLE",
						["health"] = { ["text_format"] = "" },
						["height"] = 50,
						["name"] = { ["text_format"] = "" },
						["numGroups"] = 6,
						["pvpclassificationindicator"] = { ["enable"] = false },
						["rdebuffs"] = { ["font"] = "Expressway" },
						["verticalSpacing"] = 10,
						["width"] = 110,
					},
					["raid3"] = {
						["rdebuffs"] = { ["font"] = "Expressway" },
					},
					["tank"] = { ["enable"] = false },
					["target"] = {
						["aurabar"] = { ["enable"] = false },
						["auras"] = {
							["enable"] = false,
							["isAuraCrowdControl"] = false,
							["isAuraCrowdControlPlayer"] = false,
						},
						["buffs"] = {
							["isAuraPermanent"] = true,
							["isAuraPermanentPlayer"] = true,
							["perrow"] = 6,
							["sizeOverride"] = 20,
						},
						["castbar"] = {
							["customTextFont"] = {
								["enable"] = true,
								["font"] = "Expressway",
								["fontSize"] = 16,
								["fontStyle"] = "SHADOWOUTLINE",
							},
							["customTimeFont"] = {
								["enable"] = true,
								["font"] = "Expressway",
								["fontSize"] = 16,
								["fontStyle"] = "SHADOWOUTLINE",
							},
							["height"] = 20,
							["icon"] = false,
							["insideInfoPanel"] = false,
							["xOffsetText"] = 0,
							["xOffsetTime"] = 0,
						},
						["customTexts"] = {
							["TargetHealth"] = {
								["attachTextTo"] = "Frame",
								["enable"] = true,
								["font"] = "Expressway",
								["fontOutline"] = "SHADOWOUTLINE",
								["justifyH"] = "CENTER",
								["size"] = 24,
								["text_format"] = "||cFF29CC00[health:current:shortvalue] - [perhp<%]||r",
								["xOffset"] = 0,
								["yOffset"] = 0,
							},
							["TargetName"] = {
								["attachTextTo"] = "Health",
								["enable"] = true,
								["font"] = "Expressway",
								["fontOutline"] = "SHADOWOUTLINE",
								["justifyH"] = "LEFT",
								["size"] = 22,
								["text_format"] = "[name:abbrev:medium]",
								["xOffset"] = 0,
								["yOffset"] = 28,
							},
							["TargetPower"] = {
								["attachTextTo"] = "Power",
								["enable"] = true,
								["font"] = "Expressway",
								["fontOutline"] = "SHADOWOUTLINE",
								["justifyH"] = "RIGHT",
								["size"] = 20,
								["text_format"] = "[power:current:shortvalue] / [power:max:shortvalue]",
								["xOffset"] = 0,
								["yOffset"] = 0,
							},
						},
						["debuffs"] = { ["enable"] = false },
						["disableMouseoverGlow"] = true,
						["health"] = {
							["attachTextTo"] = "InfoPanel",
							["text_format"] = "",
						},
						["height"] = 65,
						["name"] = {
							["attachTextTo"] = "InfoPanel",
							["text_format"] = "",
						},
						["orientation"] = "LEFT",
						["power"] = {
							["attachTextTo"] = "InfoPanel",
							["height"] = 20,
							["text_format"] = "",
						},
					},
					["targettarget"] = {
						["customTexts"] = {
							["ToTName"] = {
								["attachTextTo"] = "Health",
								["enable"] = true,
								["font"] = "Expressway",
								["fontOutline"] = "SHADOWOUTLINE",
								["justifyH"] = "CENTER",
								["size"] = 20,
								["text_format"] = "[name:abbrev:medium]",
								["xOffset"] = 0,
								["yOffset"] = 0,
							},
						},
						["debuffs"] = { ["enable"] = false },
						["disableMouseoverGlow"] = true,
						["name"] = { ["text_format"] = "" },
						["power"] = { ["enable"] = false },
						["raidicon"] = {
							["attachTo"] = "LEFT",
							["enable"] = false,
							["xOffset"] = 2,
							["yOffset"] = 0,
						},
						["threatStyle"] = "GLOW",
						["width"] = 165,
					},
				},
			},
		},

		-- private :: written into E.private (character-bound)
		private = {
			["WT"] = {
				["item"] = {
					["extendMerchantPages"] = { ["enable"] = true },
				},
				["maps"] = {
					["instanceDifficulty"] = {
						["enable"] = true,
						["font"] = { ["size"] = 18, ["style"] = "SHADOWOUTLINE" },
					},
					["minimapButtons"] = {
						["backdropSpacing"] = 0,
						["ignorePatterns"] = "^PlumberLandingPageMinimapButton",
						["mouseOver"] = true,
						["sortingPriority"] = "^_BugSack, _Saved, _Wind",
					},
					["superTracker"] = { ["noLimit"] = true },
					["worldMap"] = { ["scale"] = { ["size"] = 1 } },
				},
				["misc"] = {
					["lfgList"] = { ["enable"] = false },
				},
				["skins"] = {
					["addons"] = {
						["bigWigs"] = false,
						["bigWigsQueueTimer"] = false,
					},
					["blizzard"] = {
						["cooldownViewer"] = false,
					},
					["damageMeter"] = {
						["scrollBar"] = "hide",
						["windowBackdrop"] = "mouseover",
					},
				},
				["tooltips"] = {
					["factionIcon"] = false,
					["objectiveProgress"] = { ["enable"] = false },
					["petIcon"] = false,
					["petId"] = false,
					["progression"] = { ["enable"] = false },
					["tierSet"] = false,
					["titleIcon"] = { ["enable"] = false },
				},
				["unitFrames"] = {
					["roleIcon"] = { ["enable"] = false },
					["tags"] = { ["enable"] = false },
				},
			},
			["bags"] = { ["enable"] = false },
			["general"] = {
				["chatBubbleFont"] = "Expressway",
				["chatBubbleFontOutline"] = "SHADOWOUTLINE",
				["chatBubbleFontSize"] = 14,
				["chatBubbles"] = "nobackdrop",
				["nameplateFont"] = "Expressway",
				["nameplateFontOutline"] = "SHADOWOUTLINE",
				["nameplateFontSize"] = 12,
				["nameplateLargeFont"] = "Expressway",
				["nameplateLargeFontOutline"] = "SHADOWOUTLINE",
				["nameplateLargeFontSize"] = 14,
				["raidUtility"] = false,
			},
			-- NOTE: the source export contained ["install_complete"] = 15.13
			-- That ElvUI-version-specific value is intentionally omitted here.
			-- ElvUI.lua sets install_complete to the real installed ElvUI
			-- version at import time, so ElvUI's own installer stays hidden.
			["nameplates"] = { ["enable"] = false },
			["skins"] = { ["parchmentRemoverEnable"] = true },
			["theme"] = "class",
		},

		-- global :: written into E.global (account-wide)
		global = {
			["WT"] = {
				["core"] = {
					["elvUIVersionPopup"] = false,
					["loginMessage"] = false,
				},
			},
			["datatexts"] = {
				["customPanels"] = {
					["TopLeft"] = {
						["backdrop"] = false,
						["name"] = "TopLeft",
						["numPoints"] = 6,
						["width"] = 650,
					},
				},
			},
			["general"] = {
				["WorldMapCoordinates"] = { ["enable"] = false },
				["mapAlphaWhenMoving"] = 0.75,
			},
		},
	},

	-- Healing layout -- to be added later.
	-- Healing = {
	--     profile = { },
	--     private = { },
	--     global  = { },
	-- },

}

----------------------------------------------------------------------
-- ElvUI aura filters (applied in Step 3)
----------------------------------------------------------------------
-- The current export is empty: no custom aura filters are defined yet.
-- Once filters exist, paste the exported "filters" table here and Step 3
-- will apply them.

FloppyPrivate.Profiles.AuraFilters = {}
